### PR TITLE
Reduce object allocations

### PR DESCRIPTION
**Pull request by jukra**
When running [heap analysis](https://github.com/Shopify/heap-profiler) on our Rails application, I noticed that this gem allocates a lot of objects, and they seemed like duplicates between two files:
```
memory by gem
-----------------------------------
  12.02 MB  zxcvbn-0.1.10

  objects by gem
-----------------------------------
    187601  zxcvbn-0.1.10

objects by file
-----------------------------------
     93869  zxcvbn-0.1.10/lib/zxcvbn/frequency_lists.rb
     92938  zxcvbn-0.1.10/lib/zxcvbn/matching.rb
```

After getting rid of the `split(",")`s in `FREQUENCY_LISTS` the object count was reduced a lot. And then using `Set` instead of `Array` seemed to reduce memory usage even further:
```
memory by gem
-----------------------------------
   7.32 MB  zxcvbn-rb-edfa28eb1f71

objects by gem
-----------------------------------
     93760  zxcvbn-rb-edfa28eb1f71

objects by file
-----------------------------------
     92655  zxcvbn-rb-edfa28eb1f71/lib/zxcvbn/frequency_lists.rb
```

Do you think the change is safe? Not sure how the file is generated in the first place?

### CODE REVIEW

**Comment by formigarafa** [comment]
These results are exciting. The part of the code that It may be a cause of concern is this one: 
https://github.com/formigarafa/zxcvbn-rb/blob/master/lib/zxcvbn/matching.rb#L5-L16
```
module Zxcvbn
  module Matching
    def self.build_ranked_dict(ordered_list)
      result = {}
      # rank starts at 1, not 0
      ordered_list.each_with_index do |word, idx|
        result[word] = idx + 1
      end
      result
    end

    RANKED_DICTIONARIES = FREQUENCY_LISTS.transform_values do |lst|
      build_ranked_dict(lst)
    end
    ...
  end
end
```

As you can see `build_ranked_dict` uses the index of the word in the dictionary as a rank. 
I don't think this would cause any trouble but just the existence of `SortedSet` made me scratch my head.
The documentation for `Set`, only for `to_a` method, states "The order of elements is uncertain." https://docs.ruby-lang.org/en/master/Set.html#method-i-to_a 

But checking the code, they seem to have taken care of the iteration order in several other methods and the **documentation entry for this line is 22 years old**, https://github.com/ruby/ruby/blame/master/lib/set.rb#L338. This would be around Ruby 1.8 era.
This would make the documentation make sense back then because `Set` is implemented with hashes and their order could not be guaranteed. 

But after ruby 1.9.0 (or 1.9.2), hashes started keeping their elements order. 
So maybe we should be right with your suggestion.

Well, I think it need to be double checked but I like what I see. 🙂

**Comment by jukra** [comment]
I think `SortedSet` has a different use case, it's sorting comparing the elements inside the set with each other, for example with numbers:
```
set = SortedSet.new([2, 1, 5, 6, 4, 5, 3, 3, 3])
ary = []

set.each do |obj|
  ary << obj
end

p ary # => [1, 2, 3, 4, 5, 6]


---


set = Set.new([2, 1, 5, 6, 4, 5, 3, 3, 3])
ary = []

set.each do |obj|
  ary << obj
end

p ary # => [2, 1, 5, 6, 4, 3]
```

Maybe that "The order of elements is uncertain." was left so if they sometime in the future would make `Set` to use something else than a `Hash` as storage, it might change?

If we want to play it safe, using `Array` is fine, it also fixes the object allocation, but using `Set` over `Array` improved the memory usage even further in my testing. I guess in theory at least, `Set` should be faster than `Array`..

**Comment by formigarafa** [comment]
I only mentioned the sorted set to help you understand where my mind was. 
I definitely don't think it has any thing to do with a solution here.

I've look at the other major ruby implementations still active and they all seem to behave the same as MRI Ruby.
I've made a PR on Ruby docs, but to be honest I am not sure if I needed to follow a different approach for them to consider my PR.

I am really keen to do these changes, but let me think a bit more. I think I may find a way out so we can get all the improvements and reducing possible drawbacks.

**Comment by formigarafa** [comment]
Hey, @jukra , Do you mind checking something for me on your report again?

I am under the impression that some of the memory/objects that disappeared from memory/objects by gem have just moved to `Set` when started using it.

The real improvement made was to load the string entries as a pre-split string. I am making some tests here and I am getting same advantages by simply using the array. (without the "string".split).

If you don't mind could you see on your application if what I said make sense, please?

**Comment by jukra** [comment]
Ah yep got it! Yeah looks like no need to use `Set` over `Array`. I tested now with the latest version (https://github.com/formigarafa/zxcvbn-rb/pull/13) from and the results are good!
```
memory by gem
-----------------------------------
   7.32 MB  zxcvbn-0.1.11

objects by gem
-----------------------------------
    93769  zxcvbn-0.1.11

objects by file
-----------------------------------
     92944  zxcvbn-0.1.11/lib/zxcvbn/matching.rb
```
Thanks for your work in this gem :)

**Pull request merged**
